version: "3"

services:
  app:
    build: ../app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
